version: '3'
services:
    mysqld:
        build:
          context: .
          dockerfile: Dockerfile-mysql
        container_name: mysqld
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: headers
          MYSQL_USER: mysql
          MYSQL_PASSWORD: password
    app:
        build:
          context: .
          dockerfile: Dockerfile
        container_name: app
        depends_on:
          - mysqld
        ports:
          - 80:5000
    redis:
        image: redis:alpine
        container_name: redis
