FROM alpine:latest

LABEL org.owasp.url="https://www.owasp.org/index.php/OWASP_Secure_Headers_Project" \
  org.owasp.name="Owasp SecureHeaders Project" \
  org.owasp.description="Front-end from SecureHeaders Project" \
  org.owasp.version="v3.1.0"

ENV APP_DIR /opt/headers
ENV FLASK_APP ${APP_DIR}/web/webui.py
ENV BRANCH_TAG master

ARG BRANCH=$BRANCH_TAG
ARG URL=https://github.com/oshp/headers.git

WORKDIR ${APP_DIR}

RUN apk add --no-cache py2-pip py-setuptools gcc make build-base python2-dev git \
  && git clone --depth 1 $URL -b $BRANCH . \
  && pip2 install --upgrade pip \
  && pip2 install -r requirements.txt

EXPOSE 5000

COPY docker/docker-entrypoint.sh /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]
